# Generated by Django 3.0.5 on 2020-06-04 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('lectures', models.IntegerField()),
                ('tutorials', models.IntegerField()),
                ('practicals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('hod', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Weird')], max_length=1)),
                ('unique_id', models.IntegerField()),
                ('programme', models.CharField(choices=[('B', 'B.Tech'), ('M', 'M.Tech'), ('P', 'PhD'), ('NA', 'Not Applicable')], default='NA', max_length=2)),
                ('semester', models.IntegerField(null=True)),
                ('user_group', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('A', 'Administration')], max_length=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.IntegerField(null=True)),
                ('missed', models.IntegerField(null=True)),
                ('p_attended', models.IntegerField(null=True)),
                ('p_missed', models.IntegerField(null=True)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.CourseEnrollment')),
            ],
        ),
    ]
