# Generated by Django 3.0.5 on 2020-06-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
