# Generated by Django 3.0.5 on 2020-06-04 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_courseenrollment_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_grade', models.CharField(max_length=3)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.CourseEnrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('weightage', models.DecimalField(decimal_places=3, max_digits=3)),
                ('marks_obtained', models.DecimalField(decimal_places=3, max_digits=3)),
                ('max_marks', models.DecimalField(decimal_places=3, max_digits=3)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.CourseEnrollment')),
            ],
        ),
    ]
