# Generated by Django 3.0.5 on 2020-06-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_assessment_grades_teaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('programme', models.CharField(choices=[('B', 'B.Tech'), ('M', 'M.Tech'), ('P', 'PhD'), ('NA', 'Not Applicable')], default='NA', max_length=2)),
                ('subject_1', models.CharField(max_length=20)),
                ('subject_2', models.CharField(max_length=20)),
                ('subject_3', models.CharField(max_length=20)),
                ('subject_4', models.CharField(max_length=20)),
                ('subject_5', models.CharField(max_length=20)),
                ('subject_6', models.CharField(max_length=20)),
                ('subject_7', models.CharField(max_length=20)),
                ('subject_8', models.CharField(max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Department')),
            ],
        ),
    ]
