# Generated by Django 3.0.5 on 2020-06-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
