# Generated by Django 3.0.5 on 2020-06-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_timetable_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='User.Profile'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='User.Profile'),
        ),
        migrations.DeleteModel(
            name='Teaches',
        ),
    ]
