# Generated by Django 3.0.5 on 2020-06-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('sgpa', models.DecimalField(decimal_places=2, max_digits=2)),
                ('credits', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Profile')),
            ],
        ),
    ]
